name = "schwab-proxy"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
APP_ORIGIN = "https://andriiyamelskyi56.github.io"

[[kv_namespaces]]
binding = "TOKENS"
id = "676b8b23323f48d7b5fbf6f033cdaf6b"
